### ISSUE TITLE
Build a Nucleus: Main Checklist

### ISSUE THREAD

**Issue by chrisklus** [phetsims/build-a-nucleus#1]
# Build a Nucleus main checklist

## Design
- [ ] **Sim folder and design doc created** (Date: //)
  - [ ] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [ ] Place design doc in the sim folder
- [ ] **Sim suggestions doc reviewed** [suggestions doc](https://phet.unfuddle.com/a#/projects/9404/notebooks/3863/pages/105821)
   - [ ] *If a Port:* Unfuddle tickets reviewed ([searching tickets](https://github.com/phetsims/phet-info/blob/master/issue-info/unfuddle-ticket-search.md))
- [ ] **Learning goals and standards identified** (Date: //)
- [ ] **Design concept complete**  (Date: //)
- [ ] **Wireframes complete** (Date: //)
- [ ] **Mockups complete** (Date: //)
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion**
- [ ] **Interviews complete** (Date: //)
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //)
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests
- [ ] **Pre-publication items**
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Screen-specific screenshots for metadata service (see [naming convention](https://github.com/phetsims/website/issues/1322#issuecomment-1010320827))
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Accessibility features
  - [x] Email announcement language
  - [x] Teacher Guide created, uploaded, and added to sim design folder https://github.com/phetsims/build-a-nucleus/issues/128
  - [ ] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [ ] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [x] **Make sim visible on website** 
   - [x] Clear "Metadata caches" on the [Basic Administration Caches](https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminCachesPage) page
- [ ] **Post-publication items**
  - [ ] *If a Port:* Review legacy gold star activities, copy over if appropriate
  - [ ] Share new features, design challenges, and treats with group!
  - [ ] Email announcement
  - [ ] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Create "sim primer" issue
  - [ ] Hold postmortem if applicable (Date: 11/1/23)

## Implementation
- [x] **Repository created** (Date: 06/23/2021)
  - [x] Simulation added to [responsible_dev.json](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.json)
  - [x] Use `grunt create-sim` in perennial (see `--help` for arguments) to create the repository structure
  - [x] Collaborators added (Developer team, QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (Date: 02/07/2022) - development of a former design started in the summer of 2021 but development for the new sim started on this date
- [x] **Sim is "feature complete"** (Date: 7/28/23)
- [ ] ~**QA team "first look"** (Date: //)~
- [x] Interviews may happen around here (Date: 8/4/23)
- [x] **Self Code Review complete** (Date: 8/23/23)
- [x] **Code review checklist completed"** (Date: 8/22/23)
- [x] **Sim team sign-off** (Date: 8/14/23)
- [x] **Code review completed** (Date: 8/23/23)
- [x] **Sim dev test completed** (Date: 9/18/23)
- [x] **Sim RC tests completed** (Date: 10/16/23)
- [x] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#screenshots))
  - [x] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks - see [conventions](https://github.com/phetsims/joist/blob/master/js/CreditsNode.js))
  - [x] Add CT tests for public query parameters
- [x] **Published** (Date: 10/17/23)

## QA
- [ ] *If a Port:* **Legacy sim tested for bugs**; issues reported in repo
- [x] **Dev testing started** (Date: 9/1/23)
- [x] **Dev testing completed** (Date: 9/15/23)
- [x] **First RC published** (Date: 9/26/23)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 10/16/23)

**Comment by zepumph** [comment]
alright, I think the final steps are all on the design side. I may need to republish once we get new screenshots, but we'll talk over in https://github.com/phetsims/build-a-nucleus/issues/213
