### ISSUE TITLE
Chart Intro Screen development checklist

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#61]
Generalize DragEndedListener
- [x] create function to check a particle is within a square area and pass boolean back to listener

Periodic Table
- [x] colors to match between "highlight cell" and periodic table cell

Stable nodes
- [x] Energy label
- [x] shell model title
- [x] dotted lines on atom

**Comment by Luisav1** [comment]
Mini particle atom and energy levels
- the mini nucleus is the ParticleAtom
- the energy level represent the pseudo particle atom
- send particles in, don't add to ParticleAtom.
- send particles in to ParticleAtom with BANScreenView.addNucleonImmediatelyToAtom()
- create parallel array of protons and neutrons that would hold pseudo particles
   - link to ParticleAtom so any change in energy levels reflected in ParticleAtom
 - energy play area level node determines:
    - capture area
    - nucleon placement
    - holds pseudo particle nodes
 
Steps:
- [ ] energy level node to define capture area
   - [ ] energy levels model (keeps track of particles and levels they're at - one model for each protons/neutrons) 
      - [ ] y = 0 (lower level) , 1, 2 (higher level)
      - [ ] at y=0, x = 2, 3 ; y = 1 x = 0 - 5, y = 2, x = 0 -5
   - [ ] energy levels view ( each node grabs position info from model)
- [ ] define nucleon placement and define array of parallel protons and neutrons
- [ ] set ParticleAtom as mini nucleus

**Comment by zepumph** [comment]
Everything in https://github.com/phetsims/build-a-nucleus/issues/61#issuecomment-1299247548 has been completed over in #46. Remaining work for this screen will be done in above side issues. Closing
